### ISSUE TITLE
With duplicated data the sample app crash

### ISSUE THREAD

**Issue by FireZenk** [mrmike/DiffUtil-sample#1]
Example code:

```java
private static List<Actor> getOriginalActorList() {
        final List<Actor> actors = new ArrayList<>();

        actors.add(new Actor(1, "Jack Nicholson", 10, 1937));
        actors.add(new Actor(2, "Marlon Brando", 9, 1924));
        actors.add(new Actor(3, "Robert De Niro", 8, 1943));
        actors.add(new Actor(4, "Al Pacino", 7, 1940));
        actors.add(new Actor(5, "Daniel Day-Lewis", 6, 1957));
        actors.add(new Actor(6, "Dustin Hoffman", 5, 1937));
        actors.add(new Actor(7, "Tom Hanks", 4, 1956));
        actors.add(new Actor(8, "Anthony Hopkins", 3, 1937));
        actors.add(new Actor(9, "Paul Newman", 2, 1925));
        actors.add(new Actor(10, "Denzel Washington", 1, 1954));
        actors.add(new Actor(1, "Jack Nicholson", 10, 1937));
        actors.add(new Actor(2, "Marlon Brando", 9, 1924));
        actors.add(new Actor(3, "Robert De Niro", 8, 1943));
        actors.add(new Actor(4, "Al Pacino", 7, 1940));
        actors.add(new Actor(5, "Daniel Day-Lewis", 6, 1957));
        actors.add(new Actor(6, "Dustin Hoffman", 5, 1937));
        actors.add(new Actor(7, "Tom Hanks", 4, 1956));
        actors.add(new Actor(8, "Anthony Hopkins", 3, 1937));
        actors.add(new Actor(9, "Paul Newman", 2, 1925));
        actors.add(new Actor(10, "Denzel Washington", 1, 1954));


        return actors;
    }
```

See I only duplicate the actor entries once, and when you do some changes in the app:

```java
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2d2b513b position=20 id=-1, oldPos=11, pLpos:11 scrap [attachedScrap] tmpDetached no parent}
at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4855)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4986)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3266)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3122)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
```

**Comment by mrmike** [comment]
I'd advise to use unique items to avoid inconsistency. With duplicated objects `ActorDiffCallback` would not work properly.
